### ISSUE TITLE
Upload document error

### ISSUE THREAD

**Issue by charles331** [datvodinh/rag-chatbot#5]
Hello,

I try to upload a document on windows 11 and got an error:
![image](https://github.com/datvodinh/rag-chatbot/assets/33583981/ef139e68-ae4b-460a-af67-46aec9594aa1)

details of error:

app       | Traceback (most recent call last):
app       |   File "/usr/local/lib/python3.11/shutil.py", line 853, in move
app       |     os.rename(src, real_dst)
app       | FileNotFoundError: [Errno 2] No such file or directory: '/tmp/gradio/ea1957b6a8b742a53875fec0a987901ef9e06d26/Data_Exchange_Technical_Guide.pdf' -> '/code/data/data/Data_Exchange_Technical_Guide.pdf'
app       |
app       | During handling of the above exception, another exception occurred:
app       |
app       | Traceback (most recent call last):
app       |   File "/usr/local/lib/python3.11/site-packages/gradio/queueing.py", line 521, in process_events
app       |     response = await route_utils.call_process_api(
app       |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
app       |   File "/usr/local/lib/python3.11/site-packages/gradio/route_utils.py", line 276, in call_process_api
app       |     output = await app.get_blocks().process_api(
app       |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
app       |   File "/usr/local/lib/python3.11/site-packages/gradio/blocks.py", line 1945, in process_api
app       |     result = await self.call_function(
app       |              ^^^^^^^^^^^^^^^^^^^^^^^^^
app       |   File "/usr/local/lib/python3.11/site-packages/gradio/blocks.py", line 1513, in call_function
app       |     prediction = await anyio.to_thread.run_sync(
app       |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
app       |   File "/usr/local/lib/python3.11/site-packages/anyio/to_thread.py", line 56, in run_sync
app       |     return await get_async_backend().run_sync_in_worker_thread(
app       |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
app       |   File "/usr/local/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 2177, in run_sync_in_worker_thread
app       |     return await future
app       |            ^^^^^^^^^^^^
app       |   File "/usr/local/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 859, in run
app       |     result = context.run(func, *args)
app       |              ^^^^^^^^^^^^^^^^^^^^^^^^
app       |   File "/usr/local/lib/python3.11/site-packages/gradio/utils.py", line 831, in wrapper
app       |     response = f(*args, **kwargs)
app       |                ^^^^^^^^^^^^^^^^^^
app       |   File "/usr/local/lib/python3.11/site-packages/gradio/utils.py", line 831, in wrapper
app       |     response = f(*args, **kwargs)
app       |                ^^^^^^^^^^^^^^^^^^
app       |   File "/code/rag_chatbot/ui/ui.py", line 209, in _processing_document
app       |     shutil.move(src=file_path, dst=dest)
app       |   File "/usr/local/lib/python3.11/shutil.py", line 873, in move
app       |     copy_function(src, real_dst)
app       |   File "/usr/local/lib/python3.11/shutil.py", line 448, in copy2
app       |     copyfile(src, dst, follow_symlinks=follow_symlinks)
app       |   File "/usr/local/lib/python3.11/shutil.py", line 258, in copyfile
app       |     with open(dst, 'wb') as fdst:
app       |          ^^^^^^^^^^^^^^^
app       | FileNotFoundError: [Errno 2] No such file or directory: '/code/data/data/Data_Exchange_Technical_Guide.pdf'

**Comment by fantastic-413** [comment]
I encountered the same problem, and I solved it by adding two lines of code.
In the `_processing_document` function of the `rag_chatbot\ui\ui.py` file：
![Uploading image.png…]()

**Comment by fantastic-413** [comment]
> Hello,
> 
> I try to upload a document on windows 11 and got an error: ![image](https://private-user-images.githubusercontent.com/33583981/335880974-ef139e68-ae4b-460a-af67-46aec9594aa1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY5MDMwODEsIm5iZiI6MTcyNjkwMjc4MSwicGF0aCI6Ii8zMzU4Mzk4MS8zMzU4ODA5NzQtZWYxMzllNjgtYWU0Yi00NjBhLWFmNjctNDZhZWM5NTk0YWExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIxVDA3MTMwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUwOTM0ZGU1Nzk5ZGRlZDhkZTVlZjQ5NDE4Nzg0ZmVkNTIyYmI5MjQzODBjYmM2OGE1OWQ1OWE1OWNhMzhjNDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.OAAikqUbjFexDJKPrz8jKKLMcjfekM42-H9BnsgXr0c)
> 
> details of error:
> 
> app | Traceback (most recent call last): app | File "/usr/local/lib/python3.11/shutil.py", line 853, in move app | os.rename(src, real_dst) app | FileNotFoundError: [Errno 2] No such file or directory: '/tmp/gradio/ea1957b6a8b742a53875fec0a987901ef9e06d26/Data_Exchange_Technical_Guide.pdf' -> '/code/data/data/Data_Exchange_Technical_Guide.pdf' app | app | During handling of the above exception, another exception occurred: app | app | Traceback (most recent call last): app | File "/usr/local/lib/python3.11/site-packages/gradio/queueing.py", line 521, in process_events app | response = await route_utils.call_process_api( app | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ app | File "/usr/local/lib/python3.11/site-packages/gradio/route_utils.py", line 276, in call_process_api app | output = await app.get_blocks().process_api( app | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ app | File "/usr/local/lib/python3.11/site-packages/gradio/blocks.py", line 1945, in process_api app | result = await self.call_function( app | ^^^^^^^^^^^^^^^^^^^^^^^^^ app | File "/usr/local/lib/python3.11/site-packages/gradio/blocks.py", line 1513, in call_function app | prediction = await anyio.to_thread.run_sync( app | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ app | File "/usr/local/lib/python3.11/site-packages/anyio/to_thread.py", line 56, in run_sync app | return await get_async_backend().run_sync_in_worker_thread( app | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ app | File "/usr/local/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 2177, in run_sync_in_worker_thread app | return await future app | ^^^^^^^^^^^^ app | File "/usr/local/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 859, in run app | result = context.run(func, *args) app | ^^^^^^^^^^^^^^^^^^^^^^^^ app | File "/usr/local/lib/python3.11/site-packages/gradio/utils.py", line 831, in wrapper app | response = f(*args, **kwargs) app | ^^^^^^^^^^^^^^^^^^ app | File "/usr/local/lib/python3.11/site-packages/gradio/utils.py", line 831, in wrapper app | response = f(*args, **kwargs) app | ^^^^^^^^^^^^^^^^^^ app | File "/code/rag_chatbot/ui/ui.py", line 209, in _processing_document app | shutil.move(src=file_path, dst=dest) app | File "/usr/local/lib/python3.11/shutil.py", line 873, in move app | copy_function(src, real_dst) app | File "/usr/local/lib/python3.11/shutil.py", line 448, in copy2 app | copyfile(src, dst, follow_symlinks=follow_symlinks) app | File "/usr/local/lib/python3.11/shutil.py", line 258, in copyfile app | with open(dst, 'wb') as fdst: app | ^^^^^^^^^^^^^^^ app | FileNotFoundError: [Errno 2] No such file or directory: '/code/data/data/Data_Exchange_Technical_Guide.pdf'

I encountered the same problem, and I solved it by adding two lines of code.
In the _processing_document function of the rag_chatbot\ui\ui.py file：
![image](https://github.com/user-attachments/assets/061b1af9-5243-4005-999d-209210945627)

**Comment by gitszabolcs** [comment]
Same here, I had to manually create the data folder in /code/data, after that it worked. I guess this could be an easy fix

**Comment by fantastic-413** [comment]
I encountered the same problem, I just changed a few lines and the problem was solved. Add the following code at the beginning of the `_processing_document` method in the `rag_chatbot\ui\ui.py` file:
![image](https://github.com/user-attachments/assets/bf5aa90a-040f-4600-aad1-9772dae5cee0)
